services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgreesql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  user-service:
    build:
      context: ./user-service
    container_name: user_service
    restart: always
    env_file:
      - ./user-service/.env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - "3001:3001"
volumes:
  db-data:
