services:
  postgres_test:
    image: postgres:15
    container_name: fitness_workout_test_db
    restart: always
    env_file:
      - .env.test
    ports:
      - 5433:5432
    volumes:
      - pgtestdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d fitness_test"]
      interval: 5s
      retries: 5

volumes:
  pgtestdata:
